name = "o-tyan64"
type = "javascript"  # または 'javascript' または 'bundled'

[build]
command = "npm run build"  # ビルドコマンド

[workers_dev]
compatibility_flags = []

[site]
bucket = "./dist"  # 静的ファイルを配置するディレクトリ
entry-point = "workers-site"
